# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fakecouch}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Weiss"]
  s.date = %q{2010-02-09}
  s.description = %q{In-memory CouchDB for Couchrest and SimplyStored. Works for database and document API, by_attribute views, and for SimplyStored generated views}
  s.email = %q{info@peritor.com}
  s.files = [
    "lib/fakecouch.rb",
     "lib/fakecouch/couch_rest_http_adapter.rb",
     "lib/fakecouch/database.rb",
     "lib/fakecouch/error.rb",
     "lib/fakecouch/server.rb"
  ]
  s.homepage = %q{http://github.com/jweiss/fakecouch}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{In-memory CouchDB for Couchrest and SimplyStored}
  s.test_files = [
    "test/couch_rest_test.rb",
     "test/database_test.rb",
     "test/extended_couch_rest_test.rb",
     "test/fixtures/extended_couch_rest_fixtures.rb",
     "test/fixtures/simply_stored_fixtures.rb",
     "test/simply_stored_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<simply_stored>, [">= 0.1.12"])
    else
      s.add_dependency(%q<simply_stored>, [">= 0.1.12"])
    end
  else
    s.add_dependency(%q<simply_stored>, [">= 0.1.12"])
  end
end

