# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rocking_chair}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Weiss"]
  s.date = %q{2011-04-04}
  s.description = %q{In-memory CouchDB for Couchrest and SimplyStored. Works for database and document API, by_attribute views, and for SimplyStored generated views}
  s.email = %q{jw@innerewut.de}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.md"
  ]
  s.files = [
    "LICENSE.txt",
     "README.md",
     "lib/rocking_chair.rb",
     "lib/rocking_chair/couch_rest_http_adapter.rb",
     "lib/rocking_chair/database.rb",
     "lib/rocking_chair/error.rb",
     "lib/rocking_chair/helper.rb",
     "lib/rocking_chair/http_adapter.rb",
     "lib/rocking_chair/server.rb",
     "lib/rocking_chair/view.rb"
  ]
  s.homepage = %q{http://github.com/jweiss/rocking_chair}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{In-memory CouchDB for Couchrest and SimplyStored}
  s.test_files = [
    "test/couch_rest_test.rb",
     "test/database_test.rb",
     "test/extended_couch_rest_test.rb",
     "test/fixtures/extended_couch_rest_fixtures.rb",
     "test/fixtures/simply_stored_fixtures.rb",
     "test/simply_stored_test.rb",
     "test/test_helper.rb",
     "test/view_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<simply_stored>, [">= 0.1.12"])
      s.add_runtime_dependency(%q<rest-client>, [">= 1.6.1"])
      s.add_runtime_dependency(%q<couchrest>, [">= 1.0.1"])
    else
      s.add_dependency(%q<simply_stored>, [">= 0.1.12"])
      s.add_dependency(%q<rest-client>, [">= 1.6.1"])
      s.add_dependency(%q<couchrest>, [">= 1.0.1"])
    end
  else
    s.add_dependency(%q<simply_stored>, [">= 0.1.12"])
    s.add_dependency(%q<rest-client>, [">= 1.6.1"])
    s.add_dependency(%q<couchrest>, [">= 1.0.1"])
  end
end

